### PR TITLE
fix: the operator does not create directories properly

### PR DESCRIPTION
**Pull request by 0xff-dev**
fix: the operator does not create directories properly.

Should we add pvc?

### CODE REVIEW

**Review by Abirdcfly — APPROVED** [review]

**Review by bjwswang — CHANGES_REQUESTED** [review]
why `demo` is used as the tardir name ..

**Comment by 0xff-dev** [comment]
> why `demo` is used as the tardir name ..

Update to `/chaincodes`.

**Comment by Abirdcfly** [comment]
if change `/demo` to `/chaincodes`, the following code should be updated or setting `STORE` to `/chaincodes`?
https://github.com/bestchains/fabric-operator/blob/09876a0947bc6a5bece83b2b0cc5c9813c7e4486/pkg/offering/base/chaincode/util.go#L35-L49

**Comment by bjwswang** [comment]
> if change `/demo` to `/chaincodes`, the following code should be updated or setting `STORE` to `/chaincodes`? https://github.com/bestchains/fabric-operator/blob/09876a0947bc6a5bece83b2b0cc5c9813c7e4486/pkg/offering/base/chaincode/util.go#L35-L49

@Abirdcfly @0xff-dev how about a normalized directory name `/bestchains` and use sub-directories to indicate its usage
- `/bestchains/chaincodes`

**Review by bjwswang — APPROVED** [review]
/lgtm

**Pull request merged**
